Repository Solving-Our-Meals/ukki-back, pull requests merged in 2024-12, with the labels that each got.

#2 [FEATURE][AddInquiry]문의하기 API
  build.gradle
  build/classes/java/main/com/ohgiraffers/ukki/config/Application.class
  build/resources/main/application.properties
  build/tmp/compileJava/compileTransaction/stash-dir/UkkiBackApplication.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/ohgiraffers/ukki/config/Application.java
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
  src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
  src/main/java/com/ohgiraffers/ukki/inquiry/model/dao/InquiryMapper.java
  src/main/java/com/ohgiraffers/ukki/inquiry/model/dto/InquiryCategoryDTO.java
  src/main/java/com/ohgiraffers/ukki/inquiry/model/dto/InquiryDTO.java
  src/main/java/com/ohgiraffers/ukki/inquiry/model/service/InquiryService.java
  src/main/resources/mappers/UserMapper.xml
  src/main/resources/mappers/inquiry/inquiryMapper.xml
Labels: feature

#5 Feature/#1 add inquiry
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
Labels: bug

#10 [FEATURE][StoreDetail] 가게 상세페이지
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreDAO.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/BannerDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/KeywordDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/OperationDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/StoreDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/StoreInfoDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
  src/main/resources/mappers/StoreDetailMapper.xml
Labels: feature

#12 [FEATURE][SignupAPI]회원가입 API 생성 (미완성)
  .github/team_rules/team_rules/team_rules.md
  build.gradle
  src/main/java/com/ohgiraffers/ukki/config/MybatisConfig.java
  src/main/java/com/ohgiraffers/ukki/config/RedisConfig.java
  src/main/java/com/ohgiraffers/ukki/config/SpringConfig.java
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
  src/main/java/com/ohgiraffers/ukki/user/controller/EmailController.java
  src/main/java/com/ohgiraffers/ukki/user/controller/SignupController.java
  src/main/java/com/ohgiraffers/ukki/user/model/dao/SignupMapper.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/EmailDTO.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/SignupUserDTO.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/EmailService.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/SignupService.java
Labels: feature

#16 [Feature][Inquiry] 문의리스트 API
  src/main/java/com/ohgiraffers/ukki/common/InquiryState.java
  src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
  src/main/java/com/ohgiraffers/ukki/inquiry/model/dao/InquiryMapper.java
  src/main/java/com/ohgiraffers/ukki/inquiry/model/dto/InquiryListDTO.java
  src/main/java/com/ohgiraffers/ukki/inquiry/model/service/InquiryService.java
  src/main/java/com/ohgiraffers/ukki/report/controller/ReportController.java
  src/main/java/com/ohgiraffers/ukki/report/model/dao/ReportMapper.java
  src/main/java/com/ohgiraffers/ukki/report/model/dto/ReportDTO.java
  src/main/java/com/ohgiraffers/ukki/report/model/dto/ReportListDTO.java
  src/main/java/com/ohgiraffers/ukki/report/model/service/ReportService.java
  src/main/resources/mappers/inquiry/inquiryMapper.xml
Labels: feature

#20 [FEATURE][Signup]회원가입 API
  build.gradle
  src/main/java/com/ohgiraffers/ukki/config/RedisConfig.java
  src/main/java/com/ohgiraffers/ukki/user/controller/EmailController.java
  src/main/java/com/ohgiraffers/ukki/user/controller/SignupController.java
  src/main/java/com/ohgiraffers/ukki/user/model/dao/EmailMapper.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/EmailDTO.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/EmailService.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/SignupService.java
  src/main/resources/mappers/EmailMapper.xml
Labels: feature

#22 [FEATURE][StoreDetail] 가게 상세페이지 프로필 이미지 불러오기 구현
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
  src/main/resources/mappers/StoreDetailMapper.xml
Labels: feature

#27 [FEATURE][StoreDetail] 가게 상세페이지 메뉴 이미지 불러오기(미완성)
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
Labels: feature

#25 [FEATURE][Security]JWT토큰 & 시큐리티 (미완성)
  build.gradle
  src/main/java/com/ohgiraffers/ukki/auth/Filter/JwtFilter.java
  src/main/java/com/ohgiraffers/ukki/auth/model/service/AuthService.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
Labels: feature

#23 [FEATURE][Signup]회원가입 전체 API
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/user/controller/SignupController.java
  src/main/java/com/ohgiraffers/ukki/user/model/dao/SignupMapper.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/SignupService.java
  src/main/resources/mappers/SignupMapper.xml
Labels: feature

#32 [FEATURE][StoreDetail] 가게 메뉴 이미지 파일 불러오기 완료
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
Labels: feature

#35 [FEATURE][Inquiry] 가게문의 수정 및 삭제
  src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
  src/main/java/com/ohgiraffers/ukki/inquiry/model/dao/InquiryMapper.java
  src/main/java/com/ohgiraffers/ukki/inquiry/model/service/InquiryService.java
  src/main/resources/mappers/inquiry/inquiryMapper.xml
Labels: feature

#30 [FEATURE][LoginAndSecurity]로그인 & 시큐리티
  build.gradle
  src/main/java/com/ohgiraffers/ukki/auth/Filter/JwtFilter.java
  src/main/java/com/ohgiraffers/ukki/auth/Filter/LogoutFilter.java
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
  src/main/java/com/ohgiraffers/ukki/auth/model/dao/AuthDAO.java
  src/main/java/com/ohgiraffers/ukki/auth/model/dao/AuthMapper.java
  src/main/java/com/ohgiraffers/ukki/auth/model/dto/AuthDTO.java
  src/main/java/com/ohgiraffers/ukki/auth/model/dto/JwtTokenDTO.java
  src/main/java/com/ohgiraffers/ukki/auth/model/service/AuthService.java
  src/main/java/com/ohgiraffers/ukki/auth/model/service/JwtService.java
  src/main/java/com/ohgiraffers/ukki/auth/model/service/UserDetail.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/SignupService.java
  src/main/resources/mappers/AuthMapper.xml
Labels: feature

#37 [FIX][AddUserNo]유저번호 토큰에 저장
  src/main/java/com/ohgiraffers/ukki/auth/Filter/LogoutFilter.java
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
  src/main/java/com/ohgiraffers/ukki/auth/model/dto/AuthDTO.java
  src/main/java/com/ohgiraffers/ukki/auth/model/service/AuthService.java
  src/main/java/com/ohgiraffers/ukki/auth/model/service/JwtService.java
  src/main/java/com/ohgiraffers/ukki/user/controller/SignupController.java
  src/main/resources/mappers/AuthMapper.xml
Labels: fix

#38 [FEATURE][Report] 가게 리뷰신고 수정 및 삭제
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
  src/main/java/com/ohgiraffers/ukki/report/controller/ReportController.java
  src/main/java/com/ohgiraffers/ukki/report/model/dao/ReportMapper.java
  src/main/java/com/ohgiraffers/ukki/report/model/service/ReportService.java
  src/main/resources/mappers/report/ReportMapper.xml
Labels: feature

#41 [FEATURE][QR] QR코드 개선
  src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
  src/main/java/com/ohgiraffers/ukki/qr/controller/QrController.java
  src/main/java/com/ohgiraffers/ukki/qr/model/dao/QrMapper.java
  src/main/java/com/ohgiraffers/ukki/qr/model/dto/QrConfirmDTO.java
  src/main/java/com/ohgiraffers/ukki/qr/model/service/QrService.java
  src/main/resources/mappers/inquiry/InquiryMapper.xml
  src/main/resources/mappers/qr/QrMapper.xml
Labels: feature

#43 [FIX][SomeFix]경고 문구 수정
  src/main/java/com/ohgiraffers/ukki/auth/Filter/LogoutFilter.java
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
  src/main/java/com/ohgiraffers/ukki/auth/model/service/AuthService.java
  src/main/java/com/ohgiraffers/ukki/user/controller/EmailController.java
Labels: feature

#50 [FEATURE][Noshow]회원가입 노쇼로직 추가
  src/main/java/com/ohgiraffers/ukki/user/controller/EmailController.java
  src/main/java/com/ohgiraffers/ukki/user/model/dao/EmailMapper.java
  src/main/java/com/ohgiraffers/ukki/user/model/dao/SignupMapper.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/SignupUserDTO.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/EmailService.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/SignupService.java
  src/main/resources/mappers/EmailMapper.xml
  src/main/resources/mappers/SignupMapper.xml
Labels: feature

#52 [FEATURE][ADMIN] 관리자 대시보드 API
  src/main/java/com/ohgiraffers/ukki/admin/controller/AdminController.java
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/controller/AdminInquiryController.java
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/dao/AdminInquiryMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/dto/AdminInquiryDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/service/AdminInquiryService.java
  src/main/java/com/ohgiraffers/ukki/admin/model/dao/AdminModel.java
  src/main/java/com/ohgiraffers/ukki/admin/model/dto/AdminDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/model/service/AdminService.java
  src/main/java/com/ohgiraffers/ukki/admin/notice/controller/AdminNoticeController.java
  src/main/java/com/ohgiraffers/ukki/admin/notice/model/dao/AdminNoticeMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/notice/model/dto/AdminNoticeDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/notice/model/service/AdminNoticeService.java
  src/main/java/com/ohgiraffers/ukki/admin/reservation/controller/AdminReservationController.java
  src/main/java/com/ohgiraffers/ukki/admin/reservation/model/dao/AdminReservationMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/reservation/model/dto/AdminReservationDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/reservation/model/dto/MonthlyNoShowDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/reservation/model/dto/ThisWeekReservationDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/reservation/model/service/AdminReservationService.java
  src/main/java/com/ohgiraffers/ukki/admin/review/controller/AdminReviewController.java
  src/main/java/com/ohgiraffers/ukki/admin/review/model/dao/AdminReviewMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/review/model/dto/AdminReviewDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/review/model/service/AdminReviewService.java
  src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
  src/main/java/com/ohgiraffers/ukki/admin/store/model/dao/AdminStoreMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/store/model/dto/AdminStoreDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/store/model/dto/MonthlyRegistStoreDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/store/model/service/AdminStoreService.java
  src/main/java/com/ohgiraffers/ukki/admin/user/controller/AdminUserController.java
  src/main/java/com/ohgiraffers/ukki/admin/user/model/dao/AdminUserMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/user/model/dto/AdminUserDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/user/model/service/AdminUserService.java
  src/main/resources/mappers/admin/inquiry/AdminInquiryMapper.xml
  src/main/resources/mappers/admin/reservation/AdminReservationMapper.xml
  src/main/resources/mappers/admin/store/AdminStoreMapper.xml
Labels: feature

#53 [FEATURE][FindAll]아이디 찾기와 비밀번호 찾기 기능 구현
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
  src/main/java/com/ohgiraffers/ukki/auth/controller/FindController.java
  src/main/java/com/ohgiraffers/ukki/auth/model/dao/FindMapper.java
  src/main/java/com/ohgiraffers/ukki/auth/model/dto/FindDTO.java
  src/main/java/com/ohgiraffers/ukki/auth/model/dto/FindResponseDTO.java
  src/main/java/com/ohgiraffers/ukki/auth/model/service/FindService.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/SignupService.java
  src/main/resources/mappers/FindMapper.xml
Labels: feature

#55 [FEATURE][StoreDetail] 가게 상세 페이지 리뷰 조회
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/ReviewContentDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/ReviewDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
  src/main/resources/mappers/StoreDetailMapper.xml
Labels: feature

#57 [Fix][FixEmaiImageSize]이메일 이미지 사이즈 조정
  .github/team_rules/team_rules/team_rules.md
  src/main/java/com/ohgiraffers/ukki/user/model/service/EmailService.java
Labels: fix
