Repository Solving-Our-Meals/ukki-back, pull requests merged in 2025-02, with the labels that each got.

#343 [FIX][WEB] 도메인으로 url 변경
  src/main/java/com/ohgiraffers/ukki/config/HealthController.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
  src/main/java/com/ohgiraffers/ukki/qr/controller/QrController.java
  src/main/java/com/ohgiraffers/ukki/qr/model/service/QrService.java
  src/main/resources/application-prod.yml
Labels: fix

#345 [FIX][SecuritySettings]CookieSecure false에서 true로 변경
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
  src/main/java/com/ohgiraffers/ukki/auth/model/service/UserDetail.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
Labels: fix

#349 [Merge][ForUpdate] 우끼 업데이트
  src/main/java/com/ohgiraffers/ukki/admin/reservation/controller/AdminReservationController.java
  src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
  src/main/java/com/ohgiraffers/ukki/admin/store/model/dao/AdminStoreMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/store/model/dto/DayTimeDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/store/model/service/AdminStoreService.java
  src/main/java/com/ohgiraffers/ukki/auth/model/service/UserDetail.java
  src/main/java/com/ohgiraffers/ukki/config/HealthController.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
  src/main/java/com/ohgiraffers/ukki/qr/controller/QrController.java
  src/main/java/com/ohgiraffers/ukki/qr/model/dao/QrMapper.java
  src/main/java/com/ohgiraffers/ukki/qr/model/service/QrService.java
  src/main/resources/application-prod.yml
  src/main/resources/mappers/admin/store/AdminStoreMapper.xml
  src/main/resources/mappers/qr/QrMapper.xml
Labels: merge

#351 [FIX][FixDeleteCookies]쿠키 제거 문제 수정
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
Labels: bug, fix

#353 [FIX][ADMIN] 관리자 오류 및 Github Action 개선
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/controller/AdminInquiryController.java
  src/main/java/com/ohgiraffers/ukki/admin/reservation/controller/AdminReservationController.java
  src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
  src/main/java/com/ohgiraffers/ukki/admin/store/model/dao/AdminStoreMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/store/model/service/AdminStoreService.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
  src/main/java/com/ohgiraffers/ukki/qr/controller/QrController.java
  src/main/java/com/ohgiraffers/ukki/qr/model/dao/QrMapper.java
  src/main/java/com/ohgiraffers/ukki/qr/model/service/QrService.java
  src/main/resources/mappers/admin/inquiry/AdminInquiryMapper.xml
  src/main/resources/mappers/admin/store/AdminStoreMapper.xml
  src/main/resources/mappers/qr/QrMapper.xml
Labels: bug, fix

#354 [Merge][ForUpdate] 우끼 업데이트
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/controller/AdminInquiryController.java
  src/main/java/com/ohgiraffers/ukki/admin/reservation/controller/AdminReservationController.java
  src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
  src/main/java/com/ohgiraffers/ukki/admin/store/model/dao/AdminStoreMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/store/model/service/AdminStoreService.java
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
  src/main/java/com/ohgiraffers/ukki/qr/controller/QrController.java
  src/main/java/com/ohgiraffers/ukki/qr/model/dao/QrMapper.java
  src/main/java/com/ohgiraffers/ukki/qr/model/service/QrService.java
  src/main/resources/mappers/admin/inquiry/AdminInquiryMapper.xml
  src/main/resources/mappers/admin/store/AdminStoreMapper.xml
  src/main/resources/mappers/qr/QrMapper.xml
Labels: merge

#358 [FIX][WEEK] 예약 그래프
  src/main/resources/mappers/BossMapper.xml
Labels: fix

#356 [FIX][ADMIN] 관리자 기능 개선
  .github/workflows/cd.yml
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/controller/AdminInquiryController.java
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/dao/AdminInquiryMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/service/AdminInquiryService.java
  src/main/java/com/ohgiraffers/ukki/admin/reservation/controller/AdminReservationController.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
  src/main/java/com/ohgiraffers/ukki/inquiry/model/dao/InquiryMapper.java
  src/main/java/com/ohgiraffers/ukki/inquiry/model/service/InquiryService.java
  src/main/resources/mappers/admin/inquiry/AdminInquiryMapper.xml
  src/main/resources/mappers/admin/reservation/AdminReservationMapper.xml
  src/main/resources/mappers/qr/QrMapper.xml
Labels: fix

#359 [Merge][ForUpdate] 우끼 업데이트
  .github/workflows/cd.yml
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/controller/AdminInquiryController.java
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/dao/AdminInquiryMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/service/AdminInquiryService.java
  src/main/java/com/ohgiraffers/ukki/admin/reservation/controller/AdminReservationController.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
  src/main/java/com/ohgiraffers/ukki/inquiry/model/dao/InquiryMapper.java
  src/main/java/com/ohgiraffers/ukki/inquiry/model/service/InquiryService.java
  src/main/resources/mappers/BossMapper.xml
  src/main/resources/mappers/admin/inquiry/AdminInquiryMapper.xml
  src/main/resources/mappers/admin/reservation/AdminReservationMapper.xml
  src/main/resources/mappers/qr/QrMapper.xml
Labels: merge

#362 [FIX][FixLogout]로그아웃 수정
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReservationDTO.java
Labels: bug, fix

#363 [FIX][BOSS] 사장님 페이지 그래프 구현
  src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/WeeklyReservationCountDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
  src/main/resources/mappers/BossMapper.xml
Labels: bug, fix

#365 [FIX][Total] 전반적인 오류 수정
  src/main/resources/mappers/notice/NoticeMapper.xml
Labels: bug, fix

#366 [MERGE][ForUpdate] 우끼 업데이트
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
  src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/WeeklyReservationCountDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReservationDTO.java
  src/main/resources/mappers/BossMapper.xml
  src/main/resources/mappers/notice/NoticeMapper.xml
Labels: merge

#367 [FIX][FixLogout]로그아웃 문제 해결용
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
Labels: bug, fix

#368 [MERGE][ForUpdate] 우끼 업데이트
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
Labels: merge

#369 [FIX][FixLogout]배포 시 로그아웃 문제
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
Labels: bug

#370 [MERGE][ForUpdate] 우끼 업데이트
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
Labels: merge

#372 [FIX][ADMIN] 약간의 수정
  src/main/resources/mappers/admin/inquiry/AdminInquiryMapper.xml
  src/main/resources/mappers/admin/reservation/AdminReservationMapper.xml
  src/main/resources/mappers/admin/review/AdminReviewMapper.xml
  src/main/resources/mappers/admin/store/AdminStoreMapper.xml
  src/main/resources/mappers/admin/user/AdminUserMapper.xml
Labels: fix

#374 [FIX][FixLogout]로그아웃 고치기
  src/main/java/com/ohgiraffers/ukki/auth/Filter/LogoutFilter.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
Labels: bug, fix

#375 [MERGE][ForUpdate] 우끼 업데이트
  src/main/java/com/ohgiraffers/ukki/auth/Filter/LogoutFilter.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
  src/main/resources/mappers/admin/inquiry/AdminInquiryMapper.xml
  src/main/resources/mappers/admin/reservation/AdminReservationMapper.xml
  src/main/resources/mappers/admin/review/AdminReviewMapper.xml
  src/main/resources/mappers/admin/store/AdminStoreMapper.xml
  src/main/resources/mappers/admin/user/AdminUserMapper.xml
Labels: merge

#377 [MERGE][ForUpdate]우끼 업데이트
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
  src/main/resources/application-prod.yml
Labels: bug, fix

#378 [MERGE][ForUpdate]우끼 업데이트
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
Labels: bug, fix

#379 [FIX][ADMIN] 약간의 수정
  src/main/resources/mappers/admin/inquiry/AdminInquiryMapper.xml
  src/main/resources/mappers/admin/reservation/AdminReservationMapper.xml
  src/main/resources/mappers/admin/review/AdminReviewMapper.xml
  src/main/resources/mappers/admin/store/AdminStoreMapper.xml
Labels: fix

#380 [FIX][FixLogout]로그아웃 수정
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
Labels: bug, fix

#381 [MERGE][ForUpdate]우끼 업데이트
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
  src/main/resources/mappers/admin/inquiry/AdminInquiryMapper.xml
  src/main/resources/mappers/admin/reservation/AdminReservationMapper.xml
  src/main/resources/mappers/admin/review/AdminReviewMapper.xml
  src/main/resources/mappers/admin/store/AdminStoreMapper.xml
Labels: bug, fix

#382 [FIX][FixLogout]로그아웃 고치기
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
Labels: bug, fix

#383 [FIX][ADMIN] 약간의 수정
  src/main/resources/mappers/admin/store/AdminStoreMapper.xml
Labels: fix

#384 [MERGE][ForUpdate]우끼 업데이트
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/resources/mappers/admin/store/AdminStoreMapper.xml
Labels: bug, fix

#385 [FIX][FixLogoutForServer]서버 로그아웃 문제
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
Labels: bug, fix

#388 [FIX][FixLogout]로그아웃 완료
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
Labels: bug, fix

#389 [MERGE][ForUpdate]우끼 업데이트
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
Labels: bug, fix, merge

#390 [FIX][FixLogoutServer]로그아웃 수정
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
Labels: bug, fix

#391 [MERGE][ForUpdate]우끼 업데이트
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
Labels: bug, fix

#392 Hotfix/#387 logout
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
Labels: bug, fix

#396 fix: Fix Logout/2025-02-04
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
Labels: bug, fix

#398 [FIX][ADMIN] 약간의 수정
  src/main/java/com/ohgiraffers/ukki/qr/model/service/QrService.java
  src/main/resources/mappers/ReservationMapper.xml
  src/main/resources/mappers/admin/review/AdminReviewMapper.xml
  src/main/resources/mappers/admin/store/AdminStoreMapper.xml
Labels: fix

#401 [][]로그아웃 수정
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
Labels: bug, fix

#405 [FIX][ADMIN] 약간의 수정
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/controller/AdminInquiryController.java
  src/main/java/com/ohgiraffers/ukki/admin/notice/controller/AdminNoticeController.java
  src/main/java/com/ohgiraffers/ukki/admin/reservation/controller/AdminReservationController.java
  src/main/java/com/ohgiraffers/ukki/admin/reservation/model/dao/AdminReservationMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/reservation/model/service/AdminReservationService.java
  src/main/java/com/ohgiraffers/ukki/admin/review/controller/AdminReviewController.java
  src/main/java/com/ohgiraffers/ukki/admin/review/model/dao/AdminReviewMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/review/model/service/AdminReviewService.java
  src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
  src/main/java/com/ohgiraffers/ukki/admin/user/controller/AdminUserController.java
  src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
  src/main/java/com/ohgiraffers/ukki/qr/controller/QrController.java
  src/main/java/com/ohgiraffers/ukki/qr/model/service/QrService.java
  src/main/resources/mappers/admin/reservation/AdminReservationMapper.xml
  src/main/resources/mappers/admin/review/AdminReviewMapper.xml
Labels: fix

#406 [MERGE][ForUpdate] 우끼 업데이트
  README.md
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/controller/AdminInquiryController.java
  src/main/java/com/ohgiraffers/ukki/admin/notice/controller/AdminNoticeController.java
  src/main/java/com/ohgiraffers/ukki/admin/reservation/controller/AdminReservationController.java
  src/main/java/com/ohgiraffers/ukki/admin/reservation/model/dao/AdminReservationMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/reservation/model/service/AdminReservationService.java
  src/main/java/com/ohgiraffers/ukki/admin/review/controller/AdminReviewController.java
  src/main/java/com/ohgiraffers/ukki/admin/review/model/dao/AdminReviewMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/review/model/service/AdminReviewService.java
  src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
  src/main/java/com/ohgiraffers/ukki/admin/user/controller/AdminUserController.java
  src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
  src/main/java/com/ohgiraffers/ukki/qr/controller/QrController.java
  src/main/java/com/ohgiraffers/ukki/qr/model/service/QrService.java
  src/main/resources/mappers/admin/reservation/AdminReservationMapper.xml
  src/main/resources/mappers/admin/review/AdminReviewMapper.xml
Labels: merge
