Repository Solving-Our-Meals/ukki-back, pull requests merged in 2025-01, with the labels that each got.

#62 [FIX][ADMIN] 대시보드 무한로딩
  src/main/java/com/ohgiraffers/ukki/admin/reservation/controller/AdminReservationController.java
Labels: fix

#64 [FEATURE][StoreDetail] 가게 상세페이지 리뷰 등록
  build/classes/java/main/com/ohgiraffers/ukki/config/Application.class
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/ReviewContentDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
  src/main/resources/mappers/StoreDetailMapper.xml
Labels: feature

#67 [FIX][FixJwtToken]JWT 토큰 문제 해결
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
  src/main/java/com/ohgiraffers/ukki/auth/model/dao/AuthMapper.java
  src/main/java/com/ohgiraffers/ukki/auth/model/dto/ForJwtDTO.java
  src/main/java/com/ohgiraffers/ukki/auth/model/service/AuthService.java
  src/main/java/com/ohgiraffers/ukki/auth/model/service/JwtService.java
  src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
  src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageDTO.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/CookieService.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
  src/main/resources/mappers/AuthMapper.xml
  src/main/resources/mappers/mypage/MypageMapper.xml
Labels: fix

#72 [FEATURE][ADMIN] 관리자 회원
  src/main/java/com/ohgiraffers/ukki/admin/reservation/model/dao/AdminReservationMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/reservation/model/service/AdminReservationService.java
  src/main/java/com/ohgiraffers/ukki/admin/review/model/dao/AdminReviewMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/review/model/service/AdminReviewService.java
  src/main/java/com/ohgiraffers/ukki/admin/user/controller/AdminUserController.java
  src/main/java/com/ohgiraffers/ukki/admin/user/model/dao/AdminUserMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/user/model/dto/AdminUserActInfoDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/user/model/dto/AdminUserDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/user/model/dto/AdminUserResDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/user/model/dto/AdminUserReviewDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/user/model/service/AdminUserService.java
  src/main/java/com/ohgiraffers/ukki/common/UserRole.java
  src/main/resources/mappers/admin/reservation/AdminReservationMapper.xml
  src/main/resources/mappers/admin/review/AdminReviewMapper.xml
  src/main/resources/mappers/admin/user/AdminUserMapper.xml
Labels: feature

#73 [FIX][FixRefreshToken]리프레시 토큰 갱신 해결
  build/classes/java/main/com/ohgiraffers/ukki/config/Application.class
  src/main/java/com/ohgiraffers/ukki/auth/Filter/JwtFilter.java
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
  src/main/java/com/ohgiraffers/ukki/auth/model/service/AuthService.java
  src/main/java/com/ohgiraffers/ukki/auth/model/service/JwtService.java
Labels: bug, fix

#75 [FEATURE][RESERVATION] 예약페이지 대표사진, 프로필 사진 구현
  src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
  src/main/java/com/ohgiraffers/ukki/reservation/model/dao/ReservationMapper.java
  src/main/java/com/ohgiraffers/ukki/reservation/model/dto/ReservationStoreDTO.java
  src/main/java/com/ohgiraffers/ukki/reservation/model/dto/StoreBannerDTO.java
  src/main/java/com/ohgiraffers/ukki/reservation/model/service/ReservationService.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/resources/mappers/ReservationMapper.xml
  src/main/resources/mappers/StoreDetailMapper.xml
Labels: feature

#81 [FEATURE][Main] 메인페이지 백 연결
  src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/StoreInfoDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
  src/main/java/com/ohgiraffers/ukki/user/controller/MainController.java
  src/main/java/com/ohgiraffers/ukki/user/model/dao/MainDAO.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/MainDTO.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/MainService.java
  src/main/resources/mappers/MainMapper.xml
Labels: feature

#80 [FEATURE][ADMIN] 관리자 회원
  src/main/java/com/ohgiraffers/ukki/admin/user/controller/AdminUserController.java
  src/main/java/com/ohgiraffers/ukki/admin/user/model/dao/AdminUserMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/user/model/dto/AdminUserInfoDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/user/model/service/AdminUserService.java
  src/main/resources/mappers/admin/user/AdminUserMapper.xml
Labels: feature

#78 [FEATURE][Reservation] 가게 예약 페이지 DB 저장
  src/main/java/com/ohgiraffers/ukki/qr/controller/QrController.java
  src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
  src/main/java/com/ohgiraffers/ukki/reservation/model/dao/ReservationMapper.java
  src/main/java/com/ohgiraffers/ukki/reservation/model/dto/ReservationInfoDTO.java
  src/main/java/com/ohgiraffers/ukki/reservation/model/service/ReservationService.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/resources/mappers/ReservationMapper.xml
  src/main/resources/mappers/StoreDetailMapper.xml
Labels: feature

#83 [FIX][reservation] 예약 DB 연결 수정
  src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/resources/mappers/ReservationMapper.xml
Labels: fix

#84 [FEATURE][ADMIN] 회원 닉네임 수정, 삭제
  src/main/java/com/ohgiraffers/ukki/admin/user/controller/AdminUserController.java
  src/main/java/com/ohgiraffers/ukki/admin/user/model/dao/AdminUserMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/user/model/service/AdminUserService.java
  src/main/resources/mappers/admin/user/AdminUserMapper.xml
Labels: feature

#85 [FEATURE][Main] 메인페이지 백 연결
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
  src/main/java/com/ohgiraffers/ukki/user/controller/MainController.java
  src/main/resources/mappers/MainMapper.xml
Labels: feature

#87 [FIX][ADMIN] 회원 수정사항
  src/main/java/com/ohgiraffers/ukki/admin/user/controller/AdminUserController.java
  src/main/java/com/ohgiraffers/ukki/admin/user/model/service/AdminUserService.java
  src/main/resources/mappers/admin/user/AdminUserMapper.xml
Labels: fix

#93 [FEATURE][MainMap] 메인페이지 현재 위치 기반 가게 최단 경로 찾기
  src/main/java/com/ohgiraffers/ukki/config/AppConfig.java
  src/main/java/com/ohgiraffers/ukki/config/MybatisConfig.java
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
  src/main/java/com/ohgiraffers/ukki/user/controller/MainController.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/DirectionsRequest.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/MainDTO.java
Labels: feature

#95 [FEATURE][StoreDetail] 가게 상세페이지 리뷰 정렬
  src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/ReservationInfoDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/ReviewContentDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
  src/main/resources/mappers/StoreDetailMapper.xml
Labels: feature

#97 [FEATURE][ADMIN] 가게 정보 수정
  src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
Labels: feature

#99 [FEATURE][MypageConnectAPI]마이페이지 예약 리스트 API연결
  src/main/resources/mappers/mypage/MypageMapper.xml
Labels: feature

#102 [FEATURE][MypageReview]마이페이지 리뷰 조회 기능
  src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
  src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReviewDTO.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
  src/main/resources/mappers/mypage/MypageMapper.xml
Labels: feature

#107 [FEATURE][StoreDetail] 가게 상세페이지 리뷰 별점 / 리뷰 및 예약 시 유저 활동 업데이트
  src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
  src/main/java/com/ohgiraffers/ukki/reservation/model/dao/ReservationMapper.java
  src/main/java/com/ohgiraffers/ukki/reservation/model/service/ReservationService.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/ReviewContentDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
  src/main/resources/mappers/ReservationMapper.xml
  src/main/resources/mappers/StoreDetailMapper.xml
Labels: feature

#108 [FEATURE][MainMap] 메인 경로 백엔드
  src/main/java/com/ohgiraffers/ukki/config/AppConfig.java
  src/main/java/com/ohgiraffers/ukki/user/controller/MainController.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/DirectionsRequest.java
Labels: feature

#110 [FEATURE][ADMIN] 가게 수정 삭제
  src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
  src/main/java/com/ohgiraffers/ukki/admin/store/model/dao/AdminStoreMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/store/model/service/AdminStoreService.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/resources/mappers/admin/store/AdminStoreMapper.xml
Labels: feature

#114 [FEATURE][Main] 메인페이지 백엔드
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
Labels: feature

#116 [FIX][StoreDetail] 가게 상세페이지 리뷰 기본 이미지 구현
  src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/resources/mappers/StoreDetailMapper.xml
Labels: fix

#118 [FEATURE][StoreDetail] 가게 상세페이지 예약 가능 인원에 따른 예약 버튼 활성화 여부
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/ChangedResNumInfoDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/DayResPosNumDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/StoreResPosNumDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
  src/main/resources/mappers/StoreDetailMapper.xml
Labels: feature

#125 [FEATURE][StoreDetail] 가게 상세페이지 예약 가능 인원 별 예약 버튼 활성화 여부
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/StoreResPosNumDTO.java
Labels: feature

#128 [FEATURE][StoreDetail] 가게 상세페이지 리뷰 삭제
  src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
  src/main/resources/mappers/StoreDetailMapper.xml
Labels: feature

#129 [FEATURE][ADMIN] 예약 상세조회 및 삭제
  src/main/java/com/ohgiraffers/ukki/admin/reservation/controller/AdminReservationController.java
  src/main/java/com/ohgiraffers/ukki/admin/reservation/model/dao/AdminReservationMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/reservation/model/dto/ReservationInfoDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/reservation/model/service/AdminReservationService.java
  src/main/java/com/ohgiraffers/ukki/qr/controller/QrController.java
  src/main/resources/mappers/admin/reservation/AdminReservationMapper.xml
Labels: feature

#134 [FEATURE][MypageSelectInquiry]마이페이지 문의 조회
  src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
  src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageInquiryDTO.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
  src/main/resources/mappers/mypage/MypageMapper.xml
Labels: feature

#132 [FEATURE][SEARCH] 검색어 자동완성 및 실시간 인기 검색어 구현
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
  src/main/java/com/ohgiraffers/ukki/user/controller/MainController.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/SearchDTO.java
  src/main/resources/mappers/MainMapper.xml
  src/main/resources/mappers/StoreDetailMapper.xml
Labels: feature, fix

#137 [FEATURE][StoreDetail] 가게 상세페이지 리뷰 삭제
  build.gradle
  src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
  src/main/java/com/ohgiraffers/ukki/reservation/model/entity/ExpiredReservationEntity.java
  src/main/java/com/ohgiraffers/ukki/reservation/model/entity/ReservationEntity.java
  src/main/java/com/ohgiraffers/ukki/reservation/model/repository/ExpiredReservationRepository.java
  src/main/java/com/ohgiraffers/ukki/reservation/model/repository/ReservationRepository.java
  src/main/java/com/ohgiraffers/ukki/reservation/model/service/ExpiredReservationService.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
  src/main/resources/mappers/StoreDetailMapper.xml
Labels: feature

#138 [FEATURE][UpdateInquiryStatus]사용자가 답변이 달린 글을 읽었을 때 확인 완료로 변경하는 로직
  src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
  src/main/java/com/ohgiraffers/ukki/user/controller/UserController.java
  src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
  src/main/resources/mappers/mypage/MypageMapper.xml
Labels: feature

#143 [FEATURE][SEARCH] 검색페이지 백
  src/main/resources/mappers/MainMapper.xml
Labels: feature

#145 [FEATURE][UserNotice] 공지사항(사용자) 전체 조회
  src/main/java/com/ohgiraffers/ukki/notice/controller/NoticeController.java
  src/main/java/com/ohgiraffers/ukki/notice/model/dao/NoticeMapper.java
  src/main/java/com/ohgiraffers/ukki/notice/model/dto/UserNoticeDTO.java
  src/main/java/com/ohgiraffers/ukki/notice/model/service/NoticeService.java
  src/main/java/com/ohgiraffers/ukki/reservation/model/entity/ExpiredReservationEntity.java
  src/main/java/com/ohgiraffers/ukki/reservation/model/entity/ReservationEntity.java
  src/main/java/com/ohgiraffers/ukki/reservation/model/repository/ExpiredReservationRepository.java
  src/main/java/com/ohgiraffers/ukki/reservation/model/repository/ReservationRepository.java
  src/main/java/com/ohgiraffers/ukki/reservation/model/service/ExpiredReservationService.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/resources/mappers/notice/NoticeMapper.xml
Labels: feature

#146 [FEATURE][ADMIN] 리뷰 상세조회
  src/main/java/com/ohgiraffers/ukki/admin/review/controller/AdminReviewController.java
  src/main/java/com/ohgiraffers/ukki/admin/review/model/dao/AdminReviewMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/review/model/dto/ReviewInfoDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/review/model/service/AdminReviewService.java
  src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
  src/main/resources/mappers/admin/review/AdminReviewMapper.xml
Labels: feature

#155 [FIX][ADMIN] 가게 수정 이미지 이름 변경 , 가게 삭제 시 리뷰도 삭제
  src/main/java/com/ohgiraffers/ukki/admin/review/controller/AdminReviewController.java
  src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
  src/main/java/com/ohgiraffers/ukki/admin/store/model/dao/AdminStoreMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/store/model/service/AdminStoreService.java
  src/main/resources/mappers/admin/store/AdminStoreMapper.xml
Labels: fix

#157 [FIX][FixMypageFeedback]마이페이지 피드백 관련사항 수정
  src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
Labels: bug, fix

#158 [FEATURE][MypageDeleteInquiry]마이페이지 문의 삭제 로직 추가
  src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
  src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
  src/main/resources/mappers/mypage/MypageMapper.xml
Labels: feature

#161 [FEATURE][Notice] 사용자/사장님 공지사항 상세조회 백 연결
  src/main/java/com/ohgiraffers/ukki/notice/controller/NoticeController.java
  src/main/java/com/ohgiraffers/ukki/notice/model/dao/NoticeMapper.java
  src/main/java/com/ohgiraffers/ukki/notice/model/service/NoticeService.java
  src/main/resources/mappers/notice/NoticeMapper.xml
Labels: feature

#162 [FEATURE][MypageDownloadAndUpload]마이페이지 문의 파일 첨부 관련 로직
  src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
  src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageInquiryDTO.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
  src/main/resources/mappers/mypage/MypageMapper.xml
Labels: feature

#164 [FEATURE][RANDOM] 랜덤 백 구현
  src/main/java/com/ohgiraffers/ukki/reservation/model/service/ReservationService.java
  src/main/resources/mappers/BossMapper.xml
  src/main/resources/mappers/StoreDetailMapper.xml
Labels: feature

#166 [FEATURE][ADMIN] 문의 조회
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/controller/AdminInquiryController.java
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/dao/AdminInquiryMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/dto/InquiryInfoDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/dto/InquiryListDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/dto/ReportInfoDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/service/AdminInquiryService.java
  src/main/resources/mappers/admin/inquiry/AdminInquiryMapper.xml
Labels: feature

#167 [FEATURE][Notice] 사장님 공지사항 검색 기능
  src/main/java/com/ohgiraffers/ukki/notice/controller/NoticeController.java
  src/main/java/com/ohgiraffers/ukki/notice/model/dao/NoticeMapper.java
  src/main/java/com/ohgiraffers/ukki/notice/model/service/NoticeService.java
  src/main/resources/mappers/notice/NoticeMapper.xml
Labels: feature

#171 [FIX][BossNotice] 사장님 공지사항 검색 기능 수정
  src/main/java/com/ohgiraffers/ukki/notice/controller/NoticeController.java
  src/main/java/com/ohgiraffers/ukki/notice/model/dao/NoticeMapper.java
  src/main/java/com/ohgiraffers/ukki/notice/model/service/NoticeService.java
  src/main/resources/mappers/notice/NoticeMapper.xml
Labels: fix

#179 [FEATURE][MypageProfileInfo]마이페이지 프로필 정보 로직
  src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
  src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageInfoDTO.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageUpdateUserInfoDTO.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
  src/main/resources/mappers/mypage/MypageMapper.xml
Labels: feature

#174 [FEATURE][ADMIN] 문의 조회, 수정, 삭제
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/controller/AdminInquiryController.java
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/dao/AdminInquiryMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/dto/AnswerDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/service/AdminInquiryService.java
  src/main/resources/mappers/admin/inquiry/AdminInquiryMapper.xml
Labels: feature

#181 [FEATURE][ADMIN] 공지사항 생성, 수정, 삭제
  src/main/java/com/ohgiraffers/ukki/admin/notice/controller/AdminNoticeController.java
  src/main/java/com/ohgiraffers/ukki/admin/notice/model/dao/AdminNoticeMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/notice/model/service/AdminNoticeService.java
  src/main/resources/mappers/admin/notice/AdminNoticeMapper.xml
Labels: feature

#184 [FEATURE][MypageInquiryFiles]마이페이지 문의 첨부 기능 추가, 마이페이지 리뷰 삭제 로직 추가
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReviewDTO.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
  src/main/resources/mappers/mypage/MypageMapper.xml
Labels: bug, feature, fix

#191 [FEATURE][BOSSPAGE] 사장님 페이지 백
  src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
  src/main/java/com/ohgiraffers/ukki/store/controller/ReservationDTO.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/AvailableSlotsDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/WeeklyReservationCountDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
  src/main/resources/mappers/BossMapper.xml
Labels: feature

#193 [FEATURE][BossNotice] 사장님 공지사항 최근 공지사항 조회
  src/main/java/com/ohgiraffers/ukki/notice/controller/NoticeController.java
  src/main/java/com/ohgiraffers/ukki/notice/model/dao/NoticeMapper.java
  src/main/java/com/ohgiraffers/ukki/notice/model/service/NoticeService.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/resources/mappers/notice/NoticeMapper.xml
Labels: feature

#194 [FEATURE][MypageInquiryFiles]마이페이지 문의 수정 시 이전 파일 제거 로직 및 문의 첨부파일 다운로드 로직 추가
  src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
Labels: feature

#199 [FEATURE][BossReview] 사장님 페이지 리뷰 전체 조회 / 상세 조회
  src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/DetailReviewInfoDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
  src/main/resources/mappers/BossMapper.xml
Labels: feature

#209 [FIX][ADMIN] 가게 수정 주소 오류
  Dockerfile
  src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
  src/main/java/com/ohgiraffers/ukki/admin/store/model/service/AdminStoreService.java
  src/test/java/com/ohgiraffers/ukki/ApplicationTests.java
Labels: fix

#211 [FEATURE][BOSSPAGE] 사장님페이지 인원 조정 백
  src/main/java/com/ohgiraffers/ukki/reservation/model/service/ReservationService.java
  src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
  src/main/java/com/ohgiraffers/ukki/store/controller/ReservationDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
  src/main/resources/mappers/BossMapper.xml
Labels: feature

#216 [FEATURE][BossReview] 사장님 페이지 리뷰 신고 시 리뷰 신고 횟수 수정
  src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
  src/main/resources/mappers/BossMapper.xml
Labels: feature

#217 [FEATURE][MypagePDeleteAccount]마이페이지 계정 탈퇴 로직
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
  src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageDeleteAccount.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
  src/main/resources/mappers/mypage/MypageMapper.xml
Labels: feature

#221 [FEATURE][DEPLOY] 배포설정
  .dockerignore
  .github/workflows/deploy.yml
  Dockerfile
  build.gradle
  deploy.sh
  docker-compose.yml
  src/main/resources/application-prod.yml
Labels: feature

#227 [FEATURE][bossPage] 사장님 페이지 예약 날짜및 인원 조회
  src/main/java/com/ohgiraffers/ukki/reservation/model/dao/ReservationMapper.java
  src/main/java/com/ohgiraffers/ukki/reservation/model/service/ReservationService.java
  src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
  src/main/resources/mappers/BossMapper.xml
Labels: feature

#229 [FEATURE][BossInquiry] 사장님 페이지 문의 내역 상세 조회
  src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
  src/main/resources/mappers/BossMapper.xml
Labels: feature

#231 [FEATURE][BossInquiry] 사장님 페이지 문의 내역 삭제
  src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
  src/main/resources/mappers/BossMapper.xml
Labels: feature

#234 [FEATURE][MypageSearch]마이페이지 검색 기능 완료 & 문의 파일 삭제 로직 추가
  src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
  src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageInquiryDTO.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
  src/main/resources/mappers/mypage/MypageMapper.xml
Labels: feature

#240 [FEATURE][BossInquiry] 사장님 페이지 문의 수정
  src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
  src/main/resources/mappers/BossMapper.xml
Labels: feature

#243 [FEATURE][BOSS] 사장님페이지 시간별 인원 조정
  src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/DayResPosNumDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/StoreResPosNumDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/ReservationRepository.java
  src/main/resources/mappers/BossMapper.xml
Labels: feature

#244 [FEATURE][MypageDeleteAccount]마이페이지 계정 탈퇴 유저활동 삭제 추가 & 예외 상황 대응 추가
  src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
  src/main/resources/mappers/mypage/MypageMapper.xml
Labels: feature

#246 [FIX][FixSaveFilesName]문의 파일명 저장 통일 및 문의 삭제 시 파일 제거 로직 추가
  src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
  src/main/java/com/ohgiraffers/ukki/user/model/dao/MypageMapper.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
  src/main/resources/mappers/mypage/MypageMapper.xml
Labels: fix

#248 [FIX][StoreDetail, BossInquiry] 예약 중복 막기 및 그 외 수정사항
  src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
  src/main/java/com/ohgiraffers/ukki/reservation/model/dao/ReservationMapper.java
  src/main/java/com/ohgiraffers/ukki/reservation/model/service/ReservationService.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
  src/main/resources/mappers/ReservationMapper.xml
  src/main/resources/mappers/StoreDetailMapper.xml
Labels: fix

#250 [FEATURE][DeleteReservationQR]예약 취소 시 해당 QR 제거
  src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
Labels: feature

#257 [FEATURE][DEPLOY] 배포 업데이트
  .dockerignore
  .github/workflows/deploy.yml
  docker-compose.yml
  src/main/java/com/ohgiraffers/ukki/admin/user/controller/AdminUserController.java
  src/main/java/com/ohgiraffers/ukki/admin/user/model/dao/AdminUserMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/user/model/service/AdminUserService.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
  src/main/resources/application-prod.yml
  src/main/resources/mappers/admin/user/AdminUserMapper.xml
Labels: feature

#259 [FEATURE][DRIVE] 구글 드라이브 연동
  .gitignore
  build.gradle
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/controller/AdminInquiryController.java
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/dto/InquiryInfoDTO.java
  src/main/java/com/ohgiraffers/ukki/common/service/GoogleDriveService.java
  src/main/java/com/ohgiraffers/ukki/config/GoogleDriveConfig.java
  src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
  src/main/java/com/ohgiraffers/ukki/inquiry/model/dto/InquiryDTO.java
Labels: feature

#261 [FIX][WEB] LocalDate 직렬화 문제
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
Labels: fix

#263 [FIX][BOSS] 사장님페이지 수정
  src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/StoreResPosNumDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
  src/main/resources/mappers/BossMapper.xml
Labels: fix

#265 [FIX][Total] 사장님 페이지, 가게 상세페이지 오류 해결
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/DetailReviewInfoDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/InquiryDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/OperationDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/ReviewContentDTO.java
Labels: bug, fix

#267 [FIX][FixForServer]서버 배포를 위한 수정
  src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageInquiryDTO.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReservationDTO.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReservationDetailDTO.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageReviewDTO.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/UserDTO.java
  src/main/resources/mappers/StoreDetailMapper.xml
Labels: fix

#269 [FIX][FixForServerDeployment]서버 배포 수정
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
  src/main/java/com/ohgiraffers/ukki/auth/controller/FindController.java
  src/main/java/com/ohgiraffers/ukki/common/service/GoogleDriveService.java
  src/main/java/com/ohgiraffers/ukki/config/GoogleDriveConfig.java
  src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
  src/main/java/com/ohgiraffers/ukki/user/controller/EmailController.java
  src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
  src/main/java/com/ohgiraffers/ukki/user/controller/SignupController.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
Labels: fix

#275 [FIX][ALL] 서버 배포용 수정
  .dockerignore
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
  src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/WeeklyReservationCountDTO.java
  src/main/java/com/ohgiraffers/ukki/user/controller/MainController.java
  src/main/resources/mappers/BossMapper.xml
Labels: fix

#274 [FIX][Total] 서버 배포용 수정
  src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
Labels: fix

#272 [FIX][URL] 배포용 수정
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/controller/AdminInquiryController.java
  src/main/java/com/ohgiraffers/ukki/admin/notice/controller/AdminNoticeController.java
  src/main/java/com/ohgiraffers/ukki/admin/reservation/controller/AdminReservationController.java
  src/main/java/com/ohgiraffers/ukki/admin/review/controller/AdminReviewController.java
  src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
  src/main/java/com/ohgiraffers/ukki/admin/user/controller/AdminUserController.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
  src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
Labels: fix

#280 [FIX][StoreDetail] 가게 상세페이지 리뷰 작성 버그
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/ReviewContentDTO.java
Labels: bug, fix

#282 [FIX][DEPLOY] Deploy 수정
  .github/workflows/deploy.yml
Labels: fix

#284 [FIX][BOSS] 예약가능인원 수정
  src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
  src/main/resources/mappers/BossMapper.xml
Labels: fix

#289 [FEATURE][Exception] 에러 페이지 설정
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/exception/GlobalExceptionHandler.java
  src/main/java/com/ohgiraffers/ukki/exception/WebErrorController.java
  src/main/java/com/ohgiraffers/ukki/notice/controller/NoticeController.java
  src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
  src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
  src/main/resources/mappers/ReservationMapper.xml
Labels: feature

#292 [FEATURE][UploadImageAndSelectImageConnectGoogleDrive]구글 드라이브 업로드와 이미지 보이기
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/controller/AdminInquiryController.java
  src/main/java/com/ohgiraffers/ukki/common/Controller/GoogleDriveController.java
  src/main/java/com/ohgiraffers/ukki/common/service/GoogleDriveService.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
  src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
  src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
Labels: feature

#294 [FIX][ADMIN] 관리자 기능 체크
  src/main/java/com/ohgiraffers/ukki/admin/reservation/model/dto/ReservationInfoDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/reservation/model/dto/ReservationListDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
  src/main/java/com/ohgiraffers/ukki/admin/store/model/service/AdminStoreService.java
  src/main/java/com/ohgiraffers/ukki/admin/user/controller/AdminUserController.java
  src/main/java/com/ohgiraffers/ukki/admin/user/model/dao/AdminUserMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/user/model/service/AdminUserService.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
  src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
  src/main/java/com/ohgiraffers/ukki/inquiry/model/dto/InquiryListDTO.java
  src/main/java/com/ohgiraffers/ukki/inquiry/model/service/InquiryService.java
  src/main/resources/mappers/admin/store/AdminStoreMapper.xml
  src/main/resources/mappers/admin/user/AdminUserMapper.xml
Labels: fix

#296 [FEATURE][ConnectGoogleDrive]구글 드라이브 문의 수정, 삭제, 회원 탈퇴 연결
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
  src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/EmailService.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/SignupService.java
  src/main/resources/mappers/AuthMapper.xml
  src/main/resources/mappers/SignupMapper.xml
Labels: feature

#298 [FEATURE][StoreDetail] 가게 상세페이지 이미지 드라이브 연결
  src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
  src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/resources/mappers/BossMapper.xml
Labels: feature

#307 [FEATURE][RESPOSNUM] 예약가능인원 조정
  src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
  src/main/resources/mappers/BossMapper.xml
Labels: feature

#311 [FIX][GRAPH] 이번주 예약 그래프
  src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
  src/main/resources/mappers/BossMapper.xml
Labels: fix

#312 [MERGE][ForUpdate]우끼 업데이트 v
  build.gradle
  src/main/java/com/ohgiraffers/ukki/admin/reservation/controller/AdminReservationController.java
  src/main/java/com/ohgiraffers/ukki/admin/review/controller/AdminReviewController.java
  src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
  src/main/java/com/ohgiraffers/ukki/admin/store/model/dao/AdminStoreMapper.java
  src/main/java/com/ohgiraffers/ukki/admin/store/model/service/AdminStoreService.java
  src/main/java/com/ohgiraffers/ukki/common/service/GoogleDriveService.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
  src/main/java/com/ohgiraffers/ukki/inquiry/controller/InquiryController.java
  src/main/java/com/ohgiraffers/ukki/qr/controller/QrController.java
  src/main/java/com/ohgiraffers/ukki/qr/model/dao/QrMapper.java
  src/main/java/com/ohgiraffers/ukki/qr/model/service/QrService.java
  src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
  src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
  src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageDTO.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/SignupUserDTO.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/EmailService.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
  src/main/resources/mappers/AuthMapper.xml
  src/main/resources/mappers/BossMapper.xml
  src/main/resources/mappers/admin/store/AdminStoreMapper.xml
  src/main/resources/mappers/mypage/MypageMapper.xml
  src/main/resources/mappers/qr/QrMapper.xml
Labels: feature, merge

#314 메인 머지1
  .github/workflows/deploy.yml
  Dockerfile
Labels: merge

#320 [FIX][FixComplement]문제있는 부분 수정
  build.gradle
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
  src/main/java/com/ohgiraffers/ukki/common/Controller/GoogleDriveController.java
  src/main/java/com/ohgiraffers/ukki/common/service/GoogleDriveService.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
Labels: bug, fix

#322 [FIX][StoreDetail] 리뷰 작성 권한 오류
  src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/resources/mappers/StoreDetailMapper.xml
Labels: bug, fix

#326 [FIX][MAIN] 메인페이지 수정
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/java/com/ohgiraffers/ukki/user/controller/MainController.java
Labels: fix

#328 [FIX][AWS] 서버 배포 시 오류 해결
  Dockerfile
  build.gradle
  deploy.sh
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/dto/AdminInquiryListDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/service/AdminInquiryService.java
  src/main/java/com/ohgiraffers/ukki/admin/reservation/model/service/AdminReservationService.java
  src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
  src/main/java/com/ohgiraffers/ukki/admin/store/model/service/AdminStoreService.java
  src/main/java/com/ohgiraffers/ukki/config/MybatisConfig.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
  src/main/resources/application-prod.yml
  src/main/resources/mappers/admin/inquiry/AdminInquiryMapper.xml
  src/main/resources/mappers/admin/reservation/AdminReservationMapper.xml
  src/main/resources/mappers/admin/store/AdminStoreMapper.xml
Labels: bug, fix

#329 [MERGE][ForUpdate] 우끼 버전 업데이트
  Dockerfile
  build.gradle
  deploy.sh
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/dto/AdminInquiryListDTO.java
  src/main/java/com/ohgiraffers/ukki/admin/inquiry/model/service/AdminInquiryService.java
  src/main/java/com/ohgiraffers/ukki/admin/reservation/model/service/AdminReservationService.java
  src/main/java/com/ohgiraffers/ukki/admin/store/controller/AdminStoreController.java
  src/main/java/com/ohgiraffers/ukki/admin/store/model/service/AdminStoreService.java
  src/main/java/com/ohgiraffers/ukki/auth/controller/AuthController.java
  src/main/java/com/ohgiraffers/ukki/common/Controller/GoogleDriveController.java
  src/main/java/com/ohgiraffers/ukki/common/service/GoogleDriveService.java
  src/main/java/com/ohgiraffers/ukki/config/MybatisConfig.java
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
  src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/StoreMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/dto/NoReviewReservListDTO.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/StoreService.java
  src/main/java/com/ohgiraffers/ukki/user/controller/MainController.java
  src/main/java/com/ohgiraffers/ukki/user/controller/UserController.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
  src/main/resources/application-prod.yml
  src/main/resources/mappers/StoreDetailMapper.xml
  src/main/resources/mappers/admin/inquiry/AdminInquiryMapper.xml
  src/main/resources/mappers/admin/reservation/AdminReservationMapper.xml
  src/main/resources/mappers/admin/store/AdminStoreMapper.xml
Labels: merge

#331 [CHORE][EnvironmentVariable]환경 변수 수정
  src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
Labels: chore

#333 [FIX][Total] 구글 드라이브 환경 설정 수정
  src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
  src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
Labels: fix

#335 [FIX][FixMypageInquiry]마이페이지 문의 버그 수정
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
  src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageUpdateUserInfoDTO.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
  src/main/resources/mappers/mypage/MypageMapper.xml
Labels: fix

#338 [FIX][URL] URL 수정
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
  src/main/java/com/ohgiraffers/ukki/qr/controller/QrController.java
  src/main/resources/application-prod.yml
Labels: fix

#341 [Merge][ForUpdate] 우끼 업데이트
  src/main/java/com/ohgiraffers/ukki/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/ukki/config/WebConfig.java
  src/main/java/com/ohgiraffers/ukki/qr/controller/QrController.java
  src/main/java/com/ohgiraffers/ukki/reservation/controller/ReservationController.java
  src/main/java/com/ohgiraffers/ukki/store/controller/BossController.java
  src/main/java/com/ohgiraffers/ukki/store/controller/StoreController.java
  src/main/java/com/ohgiraffers/ukki/store/model/dao/BossMapper.java
  src/main/java/com/ohgiraffers/ukki/store/model/service/BossService.java
  src/main/java/com/ohgiraffers/ukki/user/controller/MypageController.java
  src/main/java/com/ohgiraffers/ukki/user/model/dto/MypageUpdateUserInfoDTO.java
  src/main/java/com/ohgiraffers/ukki/user/model/service/MypageService.java
  src/main/resources/application-prod.yml
  src/main/resources/mappers/BossMapper.xml
  src/main/resources/mappers/mypage/MypageMapper.xml
Labels: merge
